export type CurrentWeatherType = {
  city?: string;
  weather: string;
  description: string;
  icon: string;
  temp: number;
  humidity: number;
  pressure: number;
  visibility: number;
  windSpeed: number;
  windDeg: number;
  clouds: number;
  sunset: number;
  sunrise: number;
  latitude: number;
  longitude: number;
  timezone: number;
  dateHour: number;
  uvi: number;
  feelsLike: number;
};
